[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
remappings = [
    "@fhenixprotocol/contracts/=node_modules/@fhenixprotocol/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "v4-core/=lib/v4-core/src/",
    "v4-periphery/=lib/v4-periphery/src/"
]

[rpc_endpoints]
fhenix = "${FHENIX_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
